### ISSUE TITLE
Very ugly screen flickering when paging through components

### ISSUE THREAD

**Issue by atodorov** [weldr/welder-web#164]
### Description of problem
At the Edit Recipe page I have a list of components (aka RPM packages) which is paged. When I click the next button there is an ugly flickering as the whole screen resizes for about a second. I think the reason is that when the button is clicked the area displaying available elements is cleared and it is blank untill the next page is loaded from the API. When the area is filled with components they occupy a slightly bigger area (+10px or so) which causes the browser to resize everything. 

Please see the video for more info:
https://www.youtube.com/watch?v=SLpEaYN_ynI

**Comment by jgiardino** [comment]
This issue should be resolved with #231
