### ISSUE TITLE
Update Tabs components

### ISSUE THREAD

**Issue by jgiardino** [weldr/welder-web#247]
The current implementation of Tabs is based on the source code for an old patternfly-webcomponents implementation. But a newer Tabs component in patternfly-react is available and should be used instead.

As part of this issue:
- I _think_ we can remove anything related to [webcomponents from webpack.config.js](https://github.com/weldr/welder-web/blob/master/webpack.config.js#L109). 
- The entire [Tabs](https://github.com/weldr/welder-web/tree/master/components/Tabs) folder should be removed
- The [patternfly-react Tabs component](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Tab%201%20Tittle=Tab%201&knob-Tab%202%20Tittle=Tab%202&knob-Tab%203%20Tittle=Tab%203&selectedKind=patternfly-react%2FWidgets%2FTabs&selectedStory=Basic%20Tabs%20-%20PF%20style&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) can replace all instances of the Tabs component, which occurs in the following pages/files:
  - **Blueprint page**, pages/blueprint/index.js
![image](https://user-images.githubusercontent.com/21063328/42388283-fd777c86-8112-11e8-950d-dc0e0f3776dc.png)
  - **Blueprint contents**, components/ListView/BlueprintContents.js
    - This UI displays in two places:
      - On Blueprint page, click Selected Components tab. This tab has a second set of tabs as shown below:
        ![image](https://user-images.githubusercontent.com/21063328/42388316-2543e358-8113-11e8-94bb-e9f8944a597d.png)
      - On Edit Blueprint page, in the Blueprint Components panel:
        ![image](https://user-images.githubusercontent.com/21063328/42389401-9b0c284a-8116-11e8-94e1-79d966967d60.png)
  - **Component details view**, components/ListView/ComponentDetailsView.js 
    - These tabs use the [patternfly style](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Tab%201%20Tittle=Tab%201&knob-Tab%202%20Tittle=Tab%202&knob-Tab%203%20Tittle=Tab%203&selectedKind=patternfly-react%2FWidgets%2FTabs&selectedStory=Basic%20Tabs%20-%20PF%20style&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
    - This UI displays in two places:
      - On Blueprint page, click Selected Components tab, then click the name of a component in the list view. This will display the component details view.
      - On Edit Blueprint page, click any component name (in either Available Components or Blueprint Components panels) to display the details view.
    ![image](https://user-images.githubusercontent.com/21063328/42389438-ba047630-8116-11e8-9d0a-d78ce85d27ae.png)

Additionally, there are some enhancements and issues that this update might address. If not, we should capture these as separate issues: 

**Enhancement:** When applying filters to blueprint contents, if the Dependencies tab is selected, and additional filters are applied, then the active tab switches to the Selected Components tab. Ideally, applying filters should not reset the tab selection.

**Issue:** When applying filters to blueprint contents, the numbers that display with the tab labels will update when the first filter is applied. But subsequent changes to filters (adding and removing), will not result in updates to the Dependencies tab. It's possible that switching to the patternfly-react Tabs component will address this automatically, but it not, an alternate Tab component might be needed.

**Comment by clumens** [comment]
I worked on this for a while today, and only succeeded in making the tabs vanish.  They don't show up anywhere.  You can see the changes I made in the three latest commits at https://github.com/clumens/welder-web/commits/tabs.  Any ideas would be welcome.

**Comment by jgiardino** [comment]
Where you have: `import { Tab, Tabs } from "react-patternfly-shims";`
try this instead: `import { ??? } from 'patternfly-react';`

But instead of `???`, I'm looking at the [storybook for Tabs](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Tab%201%20Tittle=Tab%201&knob-Tab%202%20Tittle=Tab%202&knob-Tab%203%20Tittle=Tab%203&selectedKind=patternfly-react%2FWidgets%2FTabs&selectedStory=Secondary%20Tabs&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs), and the example uses different components. You can see what components are being used when you click Show Info in this example.

The component that seems odd in this example is `<Uncontrolled(TabContainer)>`. Looking at the [source file for this example](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-react/src/components/Tabs/Tabs.stories.js#L78), the parent component that wraps the tabs and tab contents is `<TabContainer>`. Maybe that's what we should use instead? I'm not sure where `<Uncontrolled(TabContainer)>` is coming from or what that means.

**Comment by jgiardino** [comment]
Actually, the patternfly-react tabs are using [react-bootstrap Tabs](https://react-bootstrap.github.io/components/tabs/)

They do have examples similar to what we have now, using Tabs and Tab components. You could try that and see if they work.

The example in the patternfly-react storybook appears to be based on their [Custom Tab Layout](https://react-bootstrap.github.io/components/tabs/#tabs-custom-layout) example. If using Tabs and Tab doesn't result in the same UI that we have now, then we would want to adopt this pattern.
