### ISSUE TITLE
I'm offered to create an image from the frontpage, even though the blueprint is empty

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#254]
### Description of problem
If I'm the **edit blueprint** view, the **Create Image** button is grayed out as expected (because I have nothing to build), but if I go to the overview, there is a button to trigger the (empty) build.

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Steps to Reproduce

1. Go to the overview page listing all the blueprints
2. Press the **Create Image** button

### Actual results
**Create Image** button is active

### Expected results
**Create Image** button is inactive

![screenshot from 2018-06-28 12-58-53](https://user-images.githubusercontent.com/209895/42030543-7472ee24-7ad3-11e8-8c2d-c538deb51c8a.png)

![screenshot from 2018-06-28 12-57-20](https://user-images.githubusercontent.com/209895/42030544-749a6cba-7ad3-11e8-8ff7-0250efb697dd.png)

**Comment by andreasn** [comment]
This also goes for the curtain in the Images tab with PR #250 applied.

![screenshot from 2018-06-29 13-19-52](https://user-images.githubusercontent.com/209895/42089811-24ff5c5c-7b9f-11e8-9618-5ce53c3c0e46.png)

Should I file that as a separate issue?

**Comment by jgiardino** [comment]
Closing this one. The original issue was addressed with #268. The issue with the Images tab is noted in issue #280.
