### ISSUE TITLE
No warning that lorax-composer isn't running

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#256]
### Description of problem

I stopped the lorax-composer service, but the builder UI happily continues as if nothing is wrong.

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Expected results

The UI should give some kind of warning this is the case.

**Comment by jgiardino** [comment]
Can you elaborate on the steps to reproduce for this one? 

Also, since there is a PR for the build process, should comments about that process be captured in that PR?

**Comment by andreasn** [comment]
Hm, seems I'm having issues reproducing the issue. Might be because there service is socket activated, so it just starts lorax-composer as soon as I start the page. Might not be an issue then. Closing.
