### ISSUE TITLE
I can select several blueprints from the overview page, but there are no bulk actions to apply to them

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#257]
### Description of problem
The blueprints on the overview page have checkboxes, but checking them doesn't really serve any function (as far as I can tell). There are no bulk actions to carry out.

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Steps to Reproduce

1. Go to the overview page
2. Select two or more blueprints by checking their checkboxes
3. Now what?

### Actual results

All blueprints have checkboxes, but there are no bulk actions to carry out.

### Expected results

Either there should be bulk actions to carry out, or no checkboxes.

### Additional info

![screenshot from 2018-06-28 13-32-14](https://user-images.githubusercontent.com/209895/42031757-b26a2806-7ad7-11e8-80c3-94a40949c137.png)

**Comment by jgiardino** [comment]
This issue was updated as part of #252
