### ISSUE TITLE
Allows me to create a blueprint called "???" but then the UI breaks down pretty bad

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#259]
### Description of problem

I tried to create a blueprint called "???". When I press the **Create** button I get a 404 page.
I think there might be some limits to what you can call blueprints, but the create dialog is unable to catch those.

![screenshot from 2018-06-28 14-50-00](https://user-images.githubusercontent.com/209895/42035220-b518fd24-7ae2-11e8-8039-e6903debb4c7.png)

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Steps to Reproduce

1. Press the **Create Blueprint** button
2. Name the blueprint ???
3. You get thrown to a 404 page, because you can't name your blueprints like that

### Actual results

I can create the blueprint with the invalid name

### Expected results

I should not be able to create blueprints with invalid names.

**Comment by andreasn** [comment]
I then tried to delete the blueprint from the overview page, but it doesn't go away :/
[Screencast of the issue](https://andreasn.portknox.net/s/qSXpAzqmTwiropt)

**Comment by andreasn** [comment]
I can delete other blueprints without problems still

**Comment by andreasn** [comment]
I tried to delete the blueprint from the CLI, but I got this error:
```
[root@m1 ~]# composer-cli blueprints list
blueprints: ???, foo
[root@m1 ~]# composer-cli blueprints delete ???
2018-06-28 08:57:12,947: No JSON object could be decoded
[root@m1 ~]# 

```

**Comment by jgiardino** [comment]
@bcl Do you have documentation regarding what characters are allowed in the blueprint name?

**Comment by bcl** [comment]
Not specifically. The name is going to pass thru flask first, so things like ? and & may not work. They are then turned into a filename by replacing spaces with '-'. Anything that looks like a path will confuse flask so things like / aren't allowed. But we should have a more positive list of allowed things. I'm also not sure if UTF8 works when passed through since there are several other layers involving python and libgit.

**Comment by jgiardino** [comment]
Closing this issue since details for how we plan to address this are captured in #317
