### ISSUE TITLE
Only Imagemagick shows up in Selected Components

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#265]
### Description of problem
Only imagemagick shows up under Selected Components for me, even if I don't have any selected components at all.

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.0 on RHEL 7

### How often reproducible
Always

### Steps to Reproduce

1. Create a new blueprint
2. Check under Selected Components

### Actual results
![screenshot from 2018-06-29 16-53-45](https://user-images.githubusercontent.com/209895/42099153-02f3a834-7bbd-11e8-9f67-edcb747c0177.png)

### Expected results
That it would be either empty, or that the components I did select would show up.

**Comment by KKoukiou** [comment]
This is not relevant anymore.
When creating a new blueprint, the selected components tab looks like this:
![empty-blueprint](https://user-images.githubusercontent.com/14921356/56737514-d9378700-676a-11e9-967d-ffa429a24455.png)
