### ISSUE TITLE
no feedback if I search for a string with no matches in Available Components

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#267]
### Description of problem
If I search for a non-existing package in RHEL, say **photoshop**, under **Available Components**, I get no feedback that there isn't any matches. This works fine under **Blueprint Components** though

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Steps to Reproduce

1. Edit a blueprint
2. Search for a non-existing package, for example **photoshop**

### Actual results
No feedback

### Expected results
For it to behave in a similar way to the **Blueprint Components** filter

**Comment by jgiardino** [comment]
Isn't this a duplicate of #261? Which I closed because it's a duplicate of #249? I'm actually fine if we want to split #249 out into separate issues though. At the moment, it does cover how to communicate states, like loading vs empty, related to filtering and pagination.

**Comment by andreasn** [comment]
Sorry, you're right. I forgot. It's getting a bit too late after a long week here. Closing.
