### ISSUE TITLE
Image list order changes

### ISSUE THREAD

**Issue by jkozol** [weldr/welder-web#272]
### Description of problem

The order images are listed in changes when the API is polled to check the image status every 60s.

### Component (web, API, etc)

web

### Version or commit hash (if applicable)

0.1.0

### How often reproducible

Always

### Steps to Reproduce

1. Create an image
2. Wait 30s
3. Create a second image

### Actual results

Image 1 will display at the top of the list for 60s then image 2 will display at the top for 30s and they will continue to swap positions every 30s as one of them gets their status updated from the API.
 
### Expected results

Images sort by the order they were created in.

**Comment by bcl** [comment]
FYI on the API side of things the order should be stable until a new build is started. Currently the ordering is going to be the determined by the UUID. The other option is to sort it by the timestamp, which is the time of the last update to the build's status. Or I could change timestamp to be the time the build's metadata was written to disk (ie. the start time).
