### ISSUE TITLE
No way to download images that I have built

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#274]
### Description of problem
I can build images, but there is no way for me to download them from the UI.

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Steps to Reproduce

1. Create a blueprint
2. Add some components to it
3. Build it
4. Go to the images section and try to download it

### Actual results
There is no download button

### Expected results
There should be a download button, allowing me to download the image.

**Comment by andreasn** [comment]
This is being fixed in PR #310

**Comment by larskarlitski** [comment]
#310 was merged. Closing.
