### ISSUE TITLE
Certain image format doesn't work

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#277]
### Description of problem
I've tried to create images in all 5 formats, but as far as I can see, only 2 of them work (ext4 and tar).
If I select live-iso, partitioned-disk or qcow, they never start.

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Steps to Reproduce

1. Add some components to a blueprint
2. commit them
3. hit the Create Image button
4. Select live-iso

### Actual results
It doesn't create a live-iso image

### Expected results
That it should create a live-iso image, or the option shouldn't be there.

### Additional info
![screenshot from 2018-07-05 13-51-47](https://user-images.githubusercontent.com/209895/42322016-17142562-805b-11e8-9a81-64aef31b69bb.png)

**Comment by jgiardino** [comment]
@andreasn, @bcl Can one of you confirm if all image types work in the CLI?

**Comment by andreasn** [comment]
Yup, will try tomorrow!

**Comment by andreasn** [comment]
So it seems live-iso, partitioned-disk and qcow2 all has issues from the CLI as well.
```
[root@m1 admin]# composer-cli compose start gnome live-iso
2018-07-06 09:25:02,817: Problem depsolving gnome: There was a problem depsolving [('kernel', '*'), ('syslinux', '*'), ('efibootmgr', '*'), ('shim', '*'), ('isomd5sum', '*'), ('grub2-efi', '*'), ('memtest86+', '*'), ('shim-ia32', '*'), ('grub2', '*'), ('grub2-efi-*-cdboot', '*'), ('grub2-efi-ia32', '*')]: No package(s) available to install
```

Trying to use ext4-filesystem will as the output will happily add the build to the queue though.

**Comment by andreasn** [comment]
version 19.7.17 of composer-cli and 19.7.17 of lorax-composer

**Comment by bcl** [comment]
Is this RHEL7? And do you have the Optional repository installed on the host?

http://weldr.io/lorax/lorax-composer/lorax-composer.html#important-things-to-note
Some of the bootloader packages are in a different repo.

**Comment by andreasn** [comment]
Yup, that seemed to be the root cause!

**Comment by KKoukiou** [comment]
@andreasn  from the above conversation I guess that's resolved. If so, can we close that?

**Comment by andreasn** [comment]
I think this is fixed now, yes!
Closing.
