### ISSUE TITLE
Need ability to stop an image build in the UI

### ISSUE THREAD

**Issue by jgiardino** [weldr/welder-web#291]
### Description of problem
After an image is started in the UI, the user should be able to stop the process.

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.0

### Additional info
Refer to the [UI design document](https://docs.google.com/document/d/1O5AoTYWAoS0oyGHPofew5n3f29O90XgKp092n5eN6xY/edit?usp=sharing) for details about actions and messaging that should display as part of this workflow. 

This issue is related to #278

**Comment by andreasn** [comment]
This issue needs someone assigned to it soon.

**Comment by andreasn** [comment]
Closing this, since #347 is merged
