### ISSUE TITLE
Endless spinner

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#293]
### Description of problem
Since yesterday, when I open welder-web in Cockpit, I only get an endless spinner.

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.1

### How often reproducible
Always

### Steps to Reproduce

1. Make sure to run the latest build
2. Open the web UI

### Actual results
It's just an endless spinner

### Expected results
That the Blueprints list would show up, or the empty state

### Additional info
![screenshot from 2018-07-11 13-36-32](https://user-images.githubusercontent.com/209895/42569037-834473be-850f-11e8-97ec-3282bfea0a07.png)

Console output:
![screenshot from 2018-07-11 13-37-38](https://user-images.githubusercontent.com/209895/42569064-9b72fe92-850f-11e8-81fa-46b41433e056.png)

**Comment by andreasn** [comment]
Seems this was due to welder-web not running. Do we have an issue tracking that?

**Comment by andreasn** [comment]
We should have a warning for when lorax-composer isn't started/enabled on the system.

**Comment by larskarlitski** [comment]
#293 should fix this, except that it doesn't give a very useful error message yet.

**Comment by jkozol** [comment]
@andreasn Did starting lorax-composer fix the issue?

**Comment by andreasn** [comment]
@jkozol it did!
Here is what the Containers page in Cockpit does in a similar case.
![screenshot from 2018-07-12 23-03-35](https://user-images.githubusercontent.com/209895/42659194-d5013c3c-8627-11e8-942b-861242f09108.png)
