### ISSUE TITLE
completed image builds doesn't show up as such until I reload the page

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#306]
### Description of problem
If I trigger a build and then wait until it's done, the image won't change it's state before my eyes, but I have to reload the page. I've verified that it finished building from the CLI.

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.1

### How often reproducible
always

### Steps to Reproduce

1. create a blueprint
2. kick off a build
3. keep the image tab open wait until the build finishes

### Actual results
The image won't show up as finished

### Expected results
For it to show up as finished

**Comment by bcl** [comment]
Possibly related to this, if I start a build using composer-cli I am not seeing it show up in the UI, either while it is building, or when it is finished. I am using master from yesterday for my testing.

**Comment by KKoukiou** [comment]
This is probably fixed, I followed the exact steps that are listed above and I can't reproduce this issue.
