### ISSUE TITLE
misplaced image build state icons

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#307]
### Description of problem
The icons for the different states of the image are not always placed alongside their label, often ending up on top of the label. This looks a bit wonky.

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.1

### How often reproducible
always

### Steps to Reproduce

1. Have a bunch of images in different states
2. Open the image tab

### Actual results
icons are misplaced

### Expected results
the icons should be placed to the left of their label

### Additional info
![screenshot from 2018-07-19 12-13-57](https://user-images.githubusercontent.com/209895/42936836-8bebcd52-8b4d-11e8-9046-d99857e3a8cd.png)

**Comment by jgiardino** [comment]
Updates were included in #302 for this list, and I'm not able to reproduce this issue.

Can you confirm that you're reviewing a build that has these updates, and that you're css isn't cached?

**Comment by andreasn** [comment]
I'm not seeing this any more, so I'll close it for now. Will reopen if I run into it again.
