### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by atodorov** [weldr/welder-web#39]
It looks like the README.md file has been copied from the framework used to build the project with. Some of the sections are still useful, like Getting started, Directory layout but others appear to be unrelated to this particular project. 

@jgiardino ATM I don't know which ones can be safely deleted but I bet you do.

**Comment by petervo** [comment]
Additionally, the metadb link in the readme is broken. Should it be http://jenkins.install.bos.redhat.com/view/Composer/job/welder-deployment/lastSuccessfulBuild/artifact/metadata.db instead?

**Comment by bcl** [comment]
That should probably be removed.
