### ISSUE TITLE
image types are different between Create Image dialog and Images list

### ISSUE THREAD

**Issue by andreasn** [weldr/welder-web#407]
In the image creation dialog I get the "pretty" name, such as "Amazon Machine Image Disk (ami)", but in the Images list, I get only "ami".

![screenshot from 2018-11-15 15-03-51](https://user-images.githubusercontent.com/209895/48557703-c41b1a00-e8e7-11e8-84ae-ea0ab5d53c11.png)

**Comment by KKoukiou** [comment]
@andreasn is this a bug or it's intended to be presented like this?
The image formats are commit to be presented with their abbreviations.
When creating new images, it's good the we have the long name, but I bet afterwards, in the lists it's fine to have the abbreviation. You disagree?

**Comment by andreasn** [comment]
I wonder why I filed this.
Yeah, maybe it's fine like it is now. Unless @jgiardino has any specific thoughts on this.
I'm happy to close it.
