### ISSUE TITLE
Over 2K problems when running lint

### ISSUE THREAD

**Issue by atodorov** [weldr/welder-web#41]
As I'm learning my way through the project I run

    npm run lint

and the result was 2113 problems (2046 errors, 67 warnings)

@Neil-Smith @dcantrell not sure how you want to tackle these. I guess I need to open a Trello card for that.

**Comment by Neil-Smith** [comment]
speaking to @dcantrell he says create the card and we should start thinking about how to tackle.

**Comment by atodorov** [comment]
This is now resolved.
