### ISSUE TITLE
Selected package cannot be found in "Selected Components"

### ISSUE THREAD

**Issue by henrywang** [weldr/welder-web#415]
Package has been selected to add into blueprint, but it cannot be found in "Selected Components".
![error_firefox_2018-11-23t06-22-00 550z](https://user-images.githubusercontent.com/672230/48930419-61e79800-ef2b-11e8-85da-012dfc7b0f6b.png)

**Comment by KKoukiou** [comment]
I am not able to reproduce this. Maybe it's fixed since Nevember? Can you please confirm and close if that's the case?
