### ISSUE TITLE
Javascript and JSX code style discussion 

### ISSUE THREAD

**Issue by henrywang** [weldr/welder-web#476]
I'd like to open an issue to kick off a javascript and jsx code style discussion.
1. Formatting code and adhering to style guides can be a time-consuming and meticulous task. To make things simple I thinks we need a code formatter. After some researches, [Prettier](https://prettier.io) is an opinionated code formatter and a good choice. The final style lint settings will combine eslint and prettier settings together. The prettier will format code according to combined settings.
2. code style rules:

- [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript)
- Other rules:
```js
{
  "printWidth": 120,               // Specify the line length that the printer will wrap on
  "tabWidth": 2,                     // Specify the number of spaces per indentation-level
  "useTabs": false,                 // Indent lines with tabs instead of spaces
  "semi": true,                       // Print semicolons at the ends of statements
  "singleQuote": false,           // Use single quotes instead of double quotes
  "jsxSingleQuote": false,      // Use single quotes instead of double quotes in JSX
  "trailingComma": false,       // Print trailing commas wherever possible when multi-line
  "bracketSpacing": true,       // Print spaces between brackets in object literals. Example: { foo: bar }
  "jsxBracketSameLine": false,    // Put the > of a multi-line JSX element at the end of the last line instead of being alone on the next line
  "arrowParens": false,          // Include parentheses around a sole arrow function parameter. Example: x => x
}
```
3. Settings in `package.json` or `.eslintrc.json`. I prefer `.eslintrc.json`.
- All settings in `package.json`: all-in-one, but doesn't support comments.
- `.eslintrc.json` allows JavaScript-style comments.

**Comment by KKoukiou** [comment]
Maybe you can follow this? https://github.com/cockpit-project/starter-kit/blob/master/.eslintrc.json

**Comment by henrywang** [comment]
Thanks

> Maybe you can follow this? https://github.com/cockpit-project/starter-kit/blob/master/.eslintrc.json
> It's the suggested eslint rules for all cockpit plugins.

**Comment by jgiardino** [comment]
Great idea! Thanks for the suggestion, @KKoukiou!

**Comment by henrywang** [comment]
Thanks  @KKoukiou!
