### ISSUE TITLE
[question] where's the welder-web fedora rpm package?

### ISSUE THREAD

**Issue by angystardust** [weldr/welder-web#516]
### Description of problem
Cannot install welder-web on fedora29 via dnf/yum

### Component (web, API, etc)
welder-web

### Version or commit hash (if applicable)
n.a.

### How often reproducible
always

### Steps to Reproduce

1. open a terminal on a F29 host
2. `sudo dnf search welder` or `sudo dnf search cockpit-composer`
3. Get a sad "_No matches found_" message

### Actual results
No welder-web setup via rpm is possible.

### Expected results
Install and test welder-web

### Additional info
In the official blog, there's a mention about the setup on a F29 host but the package `cockpit-composer` nor `welder-web` doesn't exist on the fedora repos.
https://weldr.io/Pushing-Images-to-VMWare/

**Comment by martinpitt** [comment]
It wouldn't be welder-web, but cockpit-composer. This is proposed for inclusion (https://bugzilla.redhat.com/show_bug.cgi?id=1659556), but it's been stuck for a while.

**Comment by angystardust** [comment]
Thanks for the reply, @martinpitt. Is there a COPR repo that I can use 'till the approval?
Still can understand why in the blog post I linked above, there's an explicit step for cockipit-composer setup on a Fedora host... :thinking:

**Comment by martinpitt** [comment]
Yes, it's here: https://copr.fedorainfracloud.org/coprs/g/weldr/welder-web/

**Comment by angystardust** [comment]
Thank you so much! Maybe it would be helpful to mention the copr repo on the README.md ;)
