### ISSUE TITLE
Should not create an "all empty" user account

### ISSUE THREAD

**Issue by henrywang** [weldr/welder-web#625]
How to reproduce:
This issue is only able to reproduce when you first login cockpit-composer and enter into one of bluepirnt's view blueprint page, and then click Create User Account. You can see the following dialog.
![Screenshot_2019-04-06 Image Builder - localhost localdomain](https://user-images.githubusercontent.com/672230/55671611-6aca7c00-58c4-11e9-88cb-c95f0cdce8ee.png)

**Comment by KKoukiou** [comment]
@henrywang  I don't seem to be able to reproduce. Whenever I am trying to create a new user, the user input field, is auto filled with my current user.

**Comment by henrywang** [comment]
@KKoukiou, aha! Sorry for making you confused. The issue is an all-empty user can be created without any error message.
How to reproduce:
1. click "Create User Account" button.
2. click "Create" button.
Then an all-empty user will be created. And when you delete this user, an internal error was reported.
