### ISSUE TITLE
Composer says Error "not-found"

### ISSUE THREAD

**Issue by stefwalter** [weldr/welder-web#638]
### Description of problem

After installing cockpit-composer and clicking on "Image Builder" I get the following message "An Error Occurred" "not-found"

### Component (web, API, etc)

web

### Version or commit hash (if applicable)

 * cockpit-bridge-189-1.fc29.x86_64
 * cockpit-debuginfo-190-1.fc29.x86_64
 * cockpit-storaged-189-1.fc29.noarch
 * cockpit-189-1.fc29.x86_64
 * cockpit-dashboard-189-1.fc29.noarch
 * cockpit-debugsource-190-1.fc29.x86_64
 * cockpit-tests-189-1.fc29.x86_64
 * cockpit-ws-189-1.fc29.x86_64
 * cockpit-composer-0.1.9-2.fc30.noarch
 * cockpit-system-189-1.fc29.noarch
 * cockpit-networkmanager-189-1.fc29.noarch
 * cockpit-packagekit-189-1.fc29.noarch

### How often reproducible

Every time.

### Steps to Reproduce

1. Install cockpit-composer
2. Log into cockpit
3. Click on "Image Builder"

### Actual results

![Screenshot from 2019-04-17 12-59-56](https://user-images.githubusercontent.com/795070/56283359-cf31da80-6111-11e9-985e-6269f06d748e.png)

### Expected results

I would expect to be shown a screen that looks like when I click on "Containers" offering me to start docker (or in this case lorax-composer).

![Screenshot from 2019-04-17 13-00-02](https://user-images.githubusercontent.com/795070/56283414-f8526b00-6111-11e9-8d9a-b93fb777a8b9.png)

**Comment by larskarlitski** [comment]
Thanks for filing this. We're already tracking it in https://github.com/weldr/welder-web/issues/460 (alas, it's been in this state for a while.)
