### ISSUE TITLE
Packages incorrectly include themselves in their list of dependencies

### ISSUE THREAD

**Issue by stevealmy** [weldr/welder-web#72]
### Description of problem
Packages list themselves as dependencies.

### Component (web, API, etc)
API

### How often reproducible
always

### Steps to Reproduce

1. click on a package to get to the details
2. open the list of dependencies

### Actual results
notice the package itself listed here

### Expected results
a package should be listed here as its own dependency

**Comment by jgiardino** [comment]
Closing as a duplicate of #100
