### ISSUE TITLE
Cannot show Dependencies numbers for one component at Selected Components both on Edit Recipe page and Recipe page

### ISSUE THREAD

**Issue by henrywang** [weldr/welder-web#87]
### Description of problem
Cannot show Dependencies numbers for one component at Selected Components both on Edit Recipe page and Recipe page
There're two ways to display the numbers:
1. Click this component to expend this component.
2. Click right arrow button to expend this component.

### Component (web, API, etc)
Web

### How often reproducible
100%

### Steps to Reproduce

1. Select a recipe from recipe list
2. Click the recipe link to enter into recipe page or enter into edit recipe page.

### Actual results
There's no dependencies numbers in selected components.

### Expected results
The dependencies number should be here without any click.

**Comment by jgiardino** [comment]
Closing this issue. The number of dependencies has been pulled out of the list item details that are visible when collapsed, and only displays when the list item is expanded.
