### ISSUE TITLE
Two periods alert message in Create Recipe window.

### ISSUE THREAD

**Issue by henrywang** [weldr/welder-web#89]
### Description of problem
When creating a recipe without name input, there'll be an alter message in page. That alter message has two periods. "Required information is missing.."

### Component (web, API, etc)
Web

### How often reproducible
100%

### Steps to Reproduce

1. Go to Recipes page.
2. Click Create Recipe button.
3. Click Save button.

### Actual results
"Required information is missing.."

### Expected results
"Required information is missing."

### Additional info
![alert_two_periods](https://cloud.githubusercontent.com/assets/672230/25610028/356e8582-2ee7-11e7-8e7c-7ca008fe7c14.png)

**Comment by jkozol** [comment]
This will be fixed in [Pull 113](https://github.com/weldr/welder-web/pull/113).
